CREATE DATABASE bbs;

USE bbs;

CREATE TABLE bbs (
id VARCHAR(20) NOT NULL,
table_no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
table_subject VARCHAR(80) NOT NULL,
w_name VARCHAR(20) NOT NULL,
passwd VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
content TEXT NOT NULL,
url VARCHAR(80) NOT NULL,
hit INT NOT NULL,
w_date INT NOT NULL,
w_file VARCHAR(80) NOT NULL,
top INT NOT NULL, 
depth INT NOT NULL,
ip VARCHAR(15) NOT NULL);




